### ISSUE TITLE
Example page seems to be down

### ISSUE THREAD

**Issue by joaobarcia** [jazzband/django-two-factor-auth#494] opened 2022-05-06 08:54 UTC
## Expected Behavior
https://example-two-factor-auth.herokuapp.com/ should work

## Current Behavior
![Screenshot from 2022-05-06 10-52-15](https://user-images.githubusercontent.com/6717014/167099722-83845c34-9888-44b7-86bf-6fe0ca7c0c98.png)

## Context
Nothing critical, I just wanted to give you a heads up. As a new user of your project, example pages are always welcome. And usually one of the first things I check.

## Your Environment
* Browser and version: Firefox 100.0 (64-bit)

**Comment by claudep** [comment] 2022-05-06 09:25
Duplicate of #442, there is not enough manpower for that currently.

**Closed by claudep** 2022-05-06 09:25 UTC

**Comment by joaobarcia** [comment] 2022-05-06 09:47
Ah, sorry for the noise. I searched for duplicates but through the open issues.

**Comment by jcu721** [comment] 2022-05-16 22:08
I see that there's a PR submitted to update the README. 

Can we also delete the dead link in the repo description?

<img width="401" alt="Screen Shot 2022-05-16 at 6 06 28 PM" src="https://user-images.githubusercontent.com/2374425/168690155-f5bb4479-22e3-41ac-a1f9-025094fc0d8b.png">

**Comment by claudep** [comment] 2022-05-19 15:59
@jezdez, can you edit the About section?
