### ISSUE TITLE
Request not passed to `authenticate()`.

### ISSUE THREAD

**Issue by jonnyarnold** [jazzband/django-two-factor-auth#593] opened 2023-02-13 15:57 UTC
Hello 👋

I've got a bug with `django-two-factor-auth==1.15.0`. (It's [available in PyPI](https://pypi.org/project/django-two-factor-auth/1.15.0/), but [not released here on Github](https://github.com/jazzband/django-two-factor-auth/releases)?) 

To reproduce:

1. Install and configure `django==4.1.6` with `django-two-factor-auth==1.15.0` and `django-axes==5.40.1`.
2. Attempt to log in.

`django-axes` will fail with an `AxesBackendRequestParameterRequired` error, caused by a call to `authenticate()` that does not pass the current request as a parameter, as described in [their documentation](https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-authentication-backends). [Here's the error traceback.](https://github.com/jazzband/django-two-factor-auth/files/10723807/traceback.txt)

Note that downgrading to `django-two-factor-auth==1.14.0` fixes the issue, which is why I've raised a ticket here.

Let me know if I can be of any further help!

**Comment by claudep** [comment] 2023-02-19 18:41
While examining the traceback, I'm struggling to see why two-factor would be the culprit, as `authenticate` is called from Django. It would help if you could debug why the request parameter to authenticate is not passed or not detected as passed.

**Comment by claudep** [comment] 2023-02-25 09:21
Closing as more explorations are needed to demonstrate a bug in django-two-factor-auth. Feel free to reopen with more details.

**Closed by claudep** 2023-02-25 09:21 UTC

**Comment by ajakubo1** [comment] 2024-02-07 11:06
Hi!

Sure thing. Some explanations why this library is the problem for this particular bug.

I have a view ``CustomLoginView`` that is inheriting from the ``LoginView`` in ``two_factor``.

That ``CustomLoginView`` has re-defined forms:

```
    form_list = [("auth", LoginFormEdited), ("token", BackupTokenForm)]
```

Those custom forms have those ``__init__`` functions:

```
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

which is a quite common structure to use when you just want to inherit from a class and not to bother with args/kwargs that it is handling (and add some additional stuff you the ``__init__`` method).

Because of this structure, your scripts will not be able to pass all of the necessary args/kwargs to those forms. This is because of the ``get_form_kwargs`` code in your ``LoginView``:

```python
    def get_form_kwargs(self, step=None):
        if step is None:
            return {}

        form_class = self.get_form_list()[step]
        form_params = signature(form_class).parameters

        kwargs = {}
        if 'user' in form_params:
            kwargs['user'] = self.get_user()
        if 'initial_device' in form_params:
            kwargs['initial_device'] = self.get_device(step)
        if 'request' in form_params:
            kwargs['request'] = self.request
        return kwargs
```

To be more exact - this structure causes the forms to have no arguments passed, because ``form_params`` are returning ``args`` and ``kwargs`` names.

For anyone else struggling to see why forms stopped authenticating after an upgrade - this is because you did the normal thing in subclassing. What you should do as a workaround is this in your custom forms:

```python
    def __init__(self, request, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
```

Keep in mind, that you can also remove ``*args`` and ``**kwargs`` because they will be ignored in form creation with the current ``get_form_kwargs`` structure.

@claudep - this is a bug in my opinion and it should be fixed. + it should be noted as a "breaking change" in the ``changelog`` - when the change occurred (based on my research it was this commit 445a023768974a6ff74737e539bbc9c076294675).

Only suggestion that I might have for a fix - when a form is requesting ``**kwargs`` - give that form all of the available parameters that you can pass.

**Comment by sgarcialaguna-mms** [comment] 2024-02-08 12:53
I am just now upgrading an app from Django 3.2 to 4.2 and stumbled upon this issue. We use both django-axes and django-two-factor-auth.

**Comment by sgarcialaguna-mms** [comment] 2024-02-08 14:10
Here is the workaround I eventually used to get it working for me in my derived LoginView.

```python
    def get_form(self, step=None, **kwargs):
        form = super().get_form(step, **kwargs)
        form.request = self.request
        return form
```

**Comment by ajakubo1** [comment] 2024-02-08 14:32
@sgarcialaguna-mms - if you are also upgrading this library, and you used it to customize your setup token or login flow - keep in mind that most of the problems you might encounter are related to ``registry`` class instance in ``two_factor.plugins.registry``. In particular - take a close look at ``GeneratorMethod`` and ``MethodBase`` (and all of the methods it does not extend - like - ``recognize_device`` used in ``method_from_device``). This library started to dynamically hardcode its own ``Form`` classes into ``form_list`` of ``django-formtools`` lib, and some of the forms in ``form_list`` will be overridden without a warning.

Just giving you a heads-up cause I lost quite a lot of time on it already. All of the views and forms you've customised might have problems because of that.

I'm wrapping my mind around opening a proper issue for other people who might do an upgrade and wonder what is going on here.

**Comment by claudep** [comment] 2024-02-08 16:32
Note that this module is community-maintained, so if you have a suggestion to fix your issue in the form of a PR with a regression test, it has many chances to be accepted.
